### ISSUE TITLE
Remove chown from startscript?

### ISSUE THREAD

**Issue by lippoliv** [alvaroaleman/docker-backuppc#2]
Hey there,
while backing up an single Server with 2,000,000 Files, the docker Startup tooks about an hour or more (still waiting).

OK starting the Container will happen in just small cases, like updates. But why chown on each Startup?

Can you remove that, or add an ENV thatfor that Defaults to true, but provides an Option to disable chown for companys? 

I will run two Containers on one Server, one backing up this Server with the 2 Million files, and another backing up 4 Servers, maybe another 2 Million files or more (don't know at the Moment). Till now I had two vServers thatfor, but now I'll use Docker. The backups will size up to 2.6 TB (compressed).

Hope this will give you an idea why I dislike the chown command ;)

**Comment by alvaroaleman** [comment]
Hi,

The original reason for the chown was just to ensure everything works, but I've also made the experience this can take quite a lot of time.

I have made a quickfix that checks via find for unowned files before running the chown: 75f94efa234f5f3f0ffc36a9776ce2946081f5e2

It is also pushed to dockerhub using the `next` tag. Can you check if that is enough to solve your issue?

EDIT: There was a typo in the commit.

**Comment by lippoliv** [comment]
Looks quiet good, but will end in that massive downtime (was finally online 90 minutes after Container starts) as soon as one single file has wrong right.

Cant you store the found files by your `find` command, and just `chown` those files?

**Comment by lippoliv** [comment]
PS: In my case it seems like it have found data and now it sets permissions again.

**Comment by alvaroaleman** [comment]
I pushed a new version onto the `next` tag, does that fix your issue?

**Comment by lippoliv** [comment]
@alvaroaleman sorry for the late Reply

Looks like the find-command also took a Long time to run. I updated to your tag 5 Minutes ago, and it still runs. Maybe you can seperate that out to an own command in case of Users getting Errors? No Need to run it on every boot, right?

**Comment by deimosfr** [comment]
I have the same issue. Why don't you just propose an env variable RESETPERMISSION=false ? If it's set, the script will not do the chown. What do you think ?

**Comment by alvaroaleman** [comment]
@deimosfr: Sounds fine to me. Could you submit a patch for that?

**Comment by deimosfr** [comment]
Ok, I'll try asap

**Comment by deimosfr** [comment]
Can you please merge it and make a new image available on DockerHub ?

Thanks

**Comment by alvaroaleman** [comment]
Did that fix your issue @lippoliv ?

**Comment by lippoliv** [comment]
@alvaroaleman sorry for the late Reply, was really busy.

Can you move the echo into the if? It is really confusing that I see "Setting permissions" even if the script does not set permissions.

Beside this fact, it works :) NICE!
